In [2]:
#Numpy internally works on List and Dictionary
#Numpy is multidimentional

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])

In [6]:
type(a)

numpy.ndarray

In [8]:
l = range(1000)

In [10]:
a = np.arange(1000)

In [17]:
%timeit [i**2 for i in l]   #timeit ia a magic function to Calculate Time difference

251 µs ± 2.45 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
%timeit a**2

1.82 µs ± 105 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Creating Numpy Arrays

In [20]:
a =np.array([1,3,4,5,6,"udud"])

In [22]:
a.shape

(6,)

In [23]:
len(a)

6

In [27]:
b =np.array([[1,3,4,5,6,"udud"],[1,2,4,6,7]])

C:\Users\AN2025~1\AppData\Local\Temp/ipykernel_29052/1091926512.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b =np.array([[1,3,4,5,6,"udud"],[1,2,4,6,7]])


In [28]:
b

array([list([1, 3, 4, 5, 6, 'udud']), list([1, 2, 4, 6, 7])], dtype=object)

In [48]:
b

array([list([1, 3, 4, 5, 6, 'udud']), list([1, 2, 4, 6, 7])], dtype=object)

In [30]:
b.ndim

1

In [31]:
a[1]

'3'

In [32]:
a[2]

'4'

In [35]:
a = np.arange(100)

In [36]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
#Mumpy array functions

In [43]:
a = np.ones([3,4])

In [44]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [56]:
a = np.random.randint(10,40,size=(5,4))   # Random integer Creation

In [57]:
a

array([[16, 38, 30, 39],
       [25, 26, 39, 10],
       [24, 13, 28, 34],
       [36, 17, 34, 33],
       [11, 31, 39, 29]])

In [59]:
import pandas as pd


0   1   2   3
0  16  38  30  39
1  25  26  39  10
2  24  13  28  34
3  36  17  34  33
4  11  31  39  29

In [60]:
df = pd.DataFrame(a)

In [61]:
df

0   1   2   3
0  16  38  30  39
1  25  26  39  10
2  24  13  28  34
3  36  17  34  33
4  11  31  39  29

In [62]:
a=np.arange(20)

In [63]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
a[3]

3

In [65]:
a[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [66]:
a[1:10:2]

array([1, 3, 5, 7, 9])

In [73]:
a = [1,2,3,4,5]

In [74]:
b = a  #Call by reference

In [75]:
b

[1, 2, 3, 4, 5]

In [76]:
b[2] = 0

In [77]:
b

[1, 2, 0, 4, 5]

In [78]:
a

[1, 2, 0, 4, 5]

In [79]:
a = [1,2,3,4]

In [80]:
b = a[:]   # Call by Value

In [81]:
b

[1, 2, 3, 4]

In [82]:
b[2] = 0

In [83]:
b

[1, 2, 0, 4]

In [84]:
a

[1, 2, 3, 4]

In [85]:
a = np.random.randint(10,40,size=(5,4))   # Random integer Creation

In [86]:
a

array([[28, 34, 24, 17],
       [25, 15, 28, 29],
       [18, 34, 32, 24],
       [37, 35, 12, 25],
       [18, 30, 32, 11]])

In [87]:
a[2,1]

34

In [88]:
a[2,1] = 0

In [89]:
a

array([[28, 34, 24, 17],
       [25, 15, 28, 29],
       [18,  0, 32, 24],
       [37, 35, 12, 25],
       [18, 30, 32, 11]])

In [103]:
#Random logic Building Exercise

In [90]:
a = [1,2,3,4,5]
b = [1,0,3,6,7]
a1 = set(a)
b1 = set(b)

In [91]:
a1

{1, 2, 3, 4, 5}

In [92]:
b1

{0, 1, 3, 6, 7}

In [94]:
list(a1.intersection(b1))

[1, 3]

In [95]:
for i in range(len(a)):  #0,1,2,3,4
    if a[i] == b[i]:
        print(a[i])

1
3


In [100]:
a =  [1,2,3,4,5]
b = [1,0,3]

In [102]:
for i in a:
    for j in b:
        if i == j:
            print(i)

1
3


In [104]:
a = np.arange(10)

In [106]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
b = a[:5]

In [110]:
b

array([0, 1, 2, 3, 4])

In [111]:
b[2] = 10

In [112]:
b

array([ 0,  1, 10,  3,  4])

In [113]:
a

array([ 0,  1, 10,  3,  4,  5,  6,  7,  8,  9])

In [115]:
np.shares_memory(a,b)

True

In [116]:
c = a[:5].copy()

In [117]:
c

array([ 0,  1, 10,  3,  4])

In [118]:
c[2] = 20

In [119]:
c

array([ 0,  1, 20,  3,  4])

In [120]:
a

array([ 0,  1, 10,  3,  4,  5,  6,  7,  8,  9])

In [121]:
b

array([ 0,  1, 10,  3,  4])

# Basic Numpy operations

In [122]:
#1. Element Wise operations

In [123]:
a = np.array([1,2,3,4,5])

In [124]:
a

array([1, 2, 3, 4, 5])

In [127]:
a  = a * 2

In [128]:
a

array([ 4,  6,  8, 10, 12])

In [129]:
b = np.array([1,2,3,4,5])

In [130]:
b

array([1, 2, 3, 4, 5])

In [131]:
a - b

array([3, 4, 5, 6, 7])

In [132]:
a = np.array([1,2,3,4,5])

In [155]:
b = np.array([1,2,3,4,6])

In [146]:
(a==b).any()

True

In [156]:
count = 0
for i in range(len(a)):
    if a[i] == b[i]:
        count += 1
            
if count == len(a):
    print(True)
else:
    print(False)

True


In [157]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [158]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [159]:
a

array([1, 2, 3, 4, 5])

In [160]:
a.min()

1

In [161]:
a.max()

5

In [162]:
a.argmin()  # Returns Index

0

In [163]:
a.argmax()

4

In [164]:
a.mean()

3.0

In [166]:
np.median(a)

3.0

In [167]:
a.std()

1.4142135623730951

In [170]:
a = np.random.randint(10,40,size=(3,4))

In [171]:
a

array([[15, 16, 24, 20],
       [34, 16, 23, 27],
       [31, 39, 36, 19]])

In [174]:
a.reshape(2,6)

array([[15, 16, 24, 20, 34, 16],
       [23, 27, 31, 39, 36, 19]])